# -*- coding: utf-8 -*-
"""obj6_ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PnEAPkDZCtKIlI6WVMEgnpBIduVAhQY1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from google.colab import files

# This opens a file upload dialog box
uploaded = files.upload()

from google.colab import files

# This opens a file upload dialog box
uploaded = files.upload()

user_profile = pd.read_excel("user_profile.xlsx")
viewing_activity = pd.read_excel("viewing_activity.xlsx")
subscription_retention = pd.read_excel("subscription_retention.xlsx")
ratings_feedback = pd.read_excel("ratings_feedback.xlsx")
content_library = pd.read_excel("content_library.xlsx")

# Merge User Profile with Viewing Activity

ml_data = pd.merge(
    user_profile,
    viewing_activity,
    on='User_ID',
    how='inner'
)

print(ml_data.head())

# Merge Ratings Feedback

ml_data = pd.merge(
    ml_data,
    ratings_feedback[['User_ID', 'Rating']],
    on='User_ID',
    how='inner'
)

print(ml_data.head())

print("Shape of Dataset:", ml_data.shape)

ml_data.info()

ml_data.head()

ml_data['Retention_Status'] = (
    (ml_data['Completion_Percentage'] >= 50) &
    (ml_data['Rating'] >= 3)
).astype(int)

# Create Target Variable

ml_data['Retention_Status'] = (
    (ml_data['Completion_Percentage'] >= 50) &
    (ml_data['Rating'] >= 3)
).astype(int)

# Convert to labels
ml_data['Retention_Status'] = ml_data['Retention_Status'].replace({
    1: 'Retained',
    0: 'Churn Risk'
})

ml_data[['Completion_Percentage','Rating','Retention_Status']].head()

# Select Features (X)

X = ml_data[
    [
        'Age_Group',
        'Region',
        'Subscription_Type',
        'Device_Type_x',
        'Watch_Duration_Minutes',
        'Completion_Percentage',
        'Rating'
    ]
]

# Target Variable (Y)

y = ml_data['Retention_Status']

print(ml_data.columns)

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

# Encode Feature Columns

X['Age_Group'] = encoder.fit_transform(X['Age_Group'])

X['Region'] = encoder.fit_transform(X['Region'])

X['Subscription_Type'] = encoder.fit_transform(X['Subscription_Type'])

X['Device_Type_x'] = encoder.fit_transform(X['Device_Type_x'])

# Encode Target

y = encoder.fit_transform(y)

print(X.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Data :", X_train.shape)
print("Testing Data  :", X_test.shape)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("Model Trained Successfully")

# Predict on Test Data
y_pred = model.predict(X_test)

print(y_pred[:10])

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")

"""# **Task 1: Predict Future User Retention Trends**"""

# Analysis 1: Training vs Testing Data Distribution

import matplotlib.pyplot as plt

sizes = [len(X_train), len(X_test)]
labels = ['Training Data', 'Testing Data']

plt.figure(figsize=(6,6))

plt.pie(
    sizes,
    labels=labels,
    autopct='%1.1f%%',
    startangle=90,
    colors=['skyblue','orange']
)

plt.title("Training vs Testing Data Distribution")

plt.show()

# Analysis 2: Predicted User Retention Distribution

prediction = pd.Series(y_pred).value_counts()

prediction.index = ['Churn Risk', 'Retained']

plt.figure(figsize=(6,5))

plt.bar(
    prediction.index,
    prediction.values,
    color=['red','green']
)

plt.title("Predicted User Retention Distribution")
plt.xlabel("Retention Status")
plt.ylabel("Number of Users")

plt.grid(axis='y')

plt.show()

# Analysis 3: Actual vs Predicted User Retention

comparison = pd.DataFrame({
    'Actual': pd.Series(y_test).value_counts().sort_index(),
    'Predicted': pd.Series(y_pred).value_counts().sort_index()
})

comparison.index = ['Churn Risk','Retained']

comparison.plot(
    kind='bar',
    figsize=(7,5),
    color=['steelblue','orange']
)

plt.title("Actual vs Predicted User Retention")

plt.xlabel("Retention Status")
plt.ylabel("Number of Users")

plt.xticks(rotation=0)

plt.grid(axis='y')

plt.show()

"""# **Task 2: Identify Users with Churn Risk**"""

# ==========================================
# Task 2 : Identify Users with Churn Risk
# Analysis 1 : Churn Risk User Count
# ==========================================

import pandas as pd
import matplotlib.pyplot as plt

prediction = pd.Series(y_pred).value_counts().sort_index()

prediction.index = ['Churn Risk', 'Retained']

print(prediction)

plt.figure(figsize=(6,5))

plt.bar(
    prediction.index,
    prediction.values,
    color=['red','green']
)

plt.title("Predicted Churn Risk Users")
plt.xlabel("Retention Status")
plt.ylabel("Number of Users")

plt.grid(axis='y')

plt.show()

# ==========================================
# Analysis 2 : Top High-Risk Users
# ==========================================

risk_users = X_test.copy()

# Add User IDs
risk_users['User_ID'] = ml_data.loc[X_test.index, 'User_ID'].values

# Probability of Churn (Class 0)
risk_users['Churn_Probability'] = model.predict_proba(X_test)[:,0]

# Sort highest probability first
top_risk = risk_users[['User_ID','Churn_Probability']].sort_values(
    by='Churn_Probability',
    ascending=False
)

print("Top 10 High Risk Users")

top_risk.head(10)

# ==========================================
# Analysis 3 : Churn Probability Distribution
# ==========================================

probability = model.predict_proba(X_test)[:,0]

plt.figure(figsize=(7,5))

plt.hist(
    probability,
    bins=20,
    color='orange',
    edgecolor='black'
)

plt.title("Distribution of Churn Probability")
plt.xlabel("Churn Probability")
plt.ylabel("Number of Users")

plt.grid(axis='y')

plt.show()

"""# **Task 3: Evaluate Prediction Results for Business Decisions**"""

# ==========================================
# Task 3 : Evaluate Prediction Results
# Analysis 1 : Confusion Matrix
# ==========================================

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))

ConfusionMatrixDisplay.from_estimator(
    model,
    X_test,
    y_test,
    cmap='Blues'
)

plt.title("Confusion Matrix")

plt.show()

# ==========================================
# Analysis 2 : Classification Report
# ==========================================

from sklearn.metrics import classification_report
import pandas as pd

report = classification_report(
    y_test,
    y_pred,
    output_dict=True
)

report_df = pd.DataFrame(report).transpose()

print(report_df)

# ==========================================
# Analysis 3 : Model Accuracy
# ==========================================

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print(f"Model Accuracy : {accuracy*100:.2f}%")

plt.figure(figsize=(5,5))

plt.bar(
    ['Accuracy'],
    [accuracy*100],
    color='green'
)

plt.ylim(0,100)

plt.ylabel("Accuracy (%)")

plt.title("Overall Model Accuracy")

plt.grid(axis='y')

plt.show()